# Generated by Django 3.2.20 on 2023-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_audience',
            field=models.TextField(max_length=10000),
        ),
    ]
