# Generated by Django 3.2.20 on 2023-09-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0002_auto_20230903_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='category',
            name='target_audience',
        ),
    ]
