# Generated by Django 3.2.20 on 2023-09-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0005_auto_20230904_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(to='learningApp.Instructor'),
        ),
    ]
