# Generated by Django 3.2.20 on 2023-09-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0007_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='position',
            field=models.CharField(default='Position', max_length=100),
        ),
    ]
