# Generated by Django 3.2.20 on 2023-09-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0011_auto_20230909_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replyreview',
            old_name='comment',
            new_name='comment_text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent_comment',
        ),
    ]
