# Generated by Django 3.2.20 on 2023-09-10 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningApp', '0012_auto_20230910_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
