# Generated by Django 3.2.20 on 2023-09-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0015_option_quiz_quizoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningApp.lesson'),
        ),
    ]
