# Generated by Django 3.2.20 on 2023-09-14 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningApp', '0016_alter_quiz_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='quizoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='quizoption',
            name='quiz',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='title',
            new_name='option1',
        ),
        migrations.AddField(
            model_name='questions',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learningApp.lesson'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
    ]
