# Generated by Django 3.2.20 on 2023-09-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0017_auto_20230914_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
    ]
