# Generated by Django 3.2.20 on 2023-09-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0018_remove_questions_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option4',
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=1000, null=True)),
                ('option2', models.CharField(max_length=1000, null=True)),
                ('option3', models.CharField(max_length=1000, null=True)),
                ('option4', models.CharField(max_length=1000, null=True)),
                ('asks', models.TextField(max_length=1000, null=True)),
                ('answers', models.TextField(max_length=1000, null=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learningApp.lesson')),
            ],
        ),
    ]
