# Generated by Django 3.2.20 on 2023-09-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0022_useranswer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='lesson',
        ),
        migrations.AddField(
            model_name='quizscore',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learningApp.quiz'),
        ),
    ]
