# Generated by Django 3.2.20 on 2023-09-17 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningApp', '0023_auto_20230916_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('quizscore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learningApp.quizscore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
