# Generated by Django 3.2.20 on 2023-09-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0024_cumulativescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumulativescore',
            name='quizscore',
        ),
    ]
