# Generated by Django 3.2.20 on 2023-09-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0025_remove_cumulativescore_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativescore',
            name='quiz_score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learningApp.quizscore'),
        ),
    ]
