# Generated by Django 3.2.20 on 2023-09-20 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0026_cumulativescore_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativescore',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learningApp.course'),
        ),
    ]
