# Generated by Django 3.2.20 on 2023-09-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0027_cumulativescore_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativescore',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learningApp.quiz'),
        ),
    ]
