# Generated by Django 3.2.20 on 2023-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0030_auto_20230922_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('thumbnail', models.ImageField(upload_to='events')),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=10000)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
