# Generated by Django 3.2.20 on 2023-09-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0034_alter_upcomingevent_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='event_date',
            field=models.DateField(),
        ),
    ]
