# Generated by Django 3.2.20 on 2023-09-23 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0035_alter_upcomingevent_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
