# Generated by Django 3.2.20 on 2023-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0039_subscriptionnewsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
