# Generated by Django 3.2.20 on 2023-09-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0041_reviewinstructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewinstructor',
            name='instructor',
        ),
        migrations.AddField(
            model_name='reviewinstructor',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learningApp.instructor'),
        ),
    ]
