# Generated by Django 3.2.20 on 2023-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0042_auto_20230926_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinstructor',
            name='comment',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
