# Generated by Django 3.2.20 on 2023-10-02 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningApp', '0043_reviewinstructor_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enroll', models.BooleanField(default=False)),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningApp.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
